update cargo-mynew

diff --git a/bin/cargo-mynew b/bin/cargo-mynew
--- a/bin/cargo-mynew
+++ b/bin/cargo-mynew
@@ -38,15 +38,130 @@ if [ ! -d $NAME ]; then
     exit 1
 fi
 
-EL=$NAME/.dir-locals.el
-if [ -e $EL ]; then
-    echo "file already found: $EL"
-    exit 1
-fi
+editorconfig() {
+    EL=$NAME/.editorconfig
+    if [ -e $EL ]; then
+        echo "file already found: $EL"
+        exit 1
+    fi
 
-cat <<EOF >$EL
-((nil . ((indent-tabs-mode . nil)))
- (rust-mode . ((rust-indent-offset . 3)))
-)
+    cat <<EOF >$EL
+root = true
+
+[*]
+charset = utf-8
+end_of_line = lf
+insert_final_newline = true
+indent_size = 4
+indent_style = space
+trim_trailing_whitespace = true
 EOF
-#echo "$EL create."
+    #echo "$EL create."
+}
+
+rustfmt() {
+    EL=$NAME/.rustfmt
+    if [ -e $EL ]; then
+        echo "file already found: $EL"
+        exit 1
+    fi
+
+    cat <<EOF >$EL
+EOF
+    #echo "$EL create."
+}
+
+cargo() {
+    EL=$NAME/Cargo.toml
+    if [ ! -e $EL ]; then
+        echo "file not found: $EL"
+        exit 1
+    fi
+
+    cat <<EOF >>$EL
+anyhow = "1.0"
+thiserror = "1.0"
+
+async-std = { version = "1.10", features = ["attributes"] }
+futures = "0.3"
+
+[dev-dependencies]
+assert_matches = "1.5"
+serial_test = "0.5"
+EOF
+    #echo "$EL create."
+}
+
+makefile() {
+    EL=$NAME/Makefile
+    if [ -e $EL ]; then
+        echo "file already found: $EL"
+        exit 1
+    fi
+
+    cat <<EOF >>$EL
+VERSION=0.20220925
+NAME=$NAME
+
+build:
+	cargo build
+
+image:
+	mkdir -p \$\$(pwd)/,container-cache && chmod 777 \$\$(pwd)/,container-cache
+	buildah bud --layers -f Dockerfile -v \$\$(pwd)/,container-cache:/target -t \$(NAME):\$(VERSION) .
+	buildah tag \$(NAME):\$(VERSION) loadwork:latest
+	buildah tag \$(NAME):latest \$(CONTAINER_REGISTRY)/loadwork:latest
+	buildah push \$(CONTAINER_REGISTRY)/\$(NAME):latest
+
+test:
+	\$(MAKE) test-doc
+
+test:
+	@RUST_BUCKTRACE=1 cargo test -- --nocapture
+
+clean:
+	find . -name "*~" -exec rm {} \;
+
+.PHONY: build test doctest itest image
+EOF
+    #echo "$EL create."
+}
+
+gitignore() {
+    EL=$NAME/.gitignore
+    if [ -e $EL ]; then
+        echo "file already found: $EL"
+        exit 1
+    fi
+
+    cat <<EOF >>$EL
+# Generated by Cargo
+# will have compiled files and executables
+debug/
+target/
+
+# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
+# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
+#Cargo.lock
+
+# These are backup files generated by rustfmt
+**/*.rs.bk
+
+# MSVC Windows builds of rustc generate these, which store debugging information
+*.pdb
+
+# emacs
+*~
+
+# temporary filenames for me
+,*
+*-
+EOF
+    #echo "$EL create."
+}
+
+editorconfig
+rustfmt
+cargo
+makefile
+gitignore
